name: jest

on:
  push:
    paths:
      - '**.ts'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Runs tests
      run: |
        npm i
        npm run jest
